### ISSUE TITLE
Item dos menus internos com âncoras não estão funcionando

### ISSUE THREAD

**Issue by everaldomatias** [redelivre/tema-coletivo#12]
Acesse [http://tema.coletivowp.com.br/da-comunidade-wp-para-a-comunidade-wp/](http://tema.coletivowp.com.br/da-comunidade-wp-para-a-comunidade-wp/) clique em DIFERENCIAIS.

**Comment by diegorojas** [comment]
Valeu Eve, mas era bobagem de configuração no menu.
 Isso ai ta configurado com Link Personalizado. Arrumei lá! valeu!
