### ISSUE TITLE
Aplicar Carrousel do JetPack no Lightbox da Seção Galeria

### ISSUE THREAD

**Issue by diegorojas** [redelivre/tema-coletivo#14]
Aplicar Carrousel do JetPack no Lightbox da Seção Galeria, substituindo ou mantendo opção para as Galerias nativas embutidas dentro do Tema.

**Comment by diegorojas** [comment]
@matheusgimenez me ajudou aqui e resolvemos por hora usando os css e js da próprio tema por hora. Por hora está melhor para o usuário final.

**Comment by rodineicosta** [comment]
@diegorojas, essa tarefa aqui pode ter alguma relação com a #41?
