### ISSUE TITLE
Adicionar filtro condicional para evitar carregamento das fontes padrão 

### ISSUE THREAD

**Issue by matheusgimenez** [redelivre/tema-coletivo#22]
Esse filtro servirá caso um tema filho/plugin queira usar uma fonte diferente, assim evita o carregamento inútil de fontes não utilizadas.

**Comment by diegorojas** [comment]
@matheusgimenez isso aqui ta feito? alguém testou? posso fechar a issue? 

Quando puder você documenta algum caso de uso pra gente?

**Comment by matheusgimenez** [comment]
Exemplo de uso (no site da brasa.art.br):

https://github.com/brasadesign/brasa-2018-theme/blob/master/functions.php#L16

O uso, é o que eu falei, você tira todas fontes padrão que estão sendo carregadas. Dessa forma, se você tiver usando outras fontes, evita um tempo de load maior de forma inutil.

Abs e fechando aqui!
