### ISSUE TITLE
Erro ao ativar o Tema

### ISSUE THREAD

**Issue by everaldomatias** [redelivre/tema-coletivo#24]
Registrando aqui o erro que apareceu ao ativar o tema. Fiz download pelo github, baixando o zip e subindo no WP pelo próprio painel.

```
Warning: Invalid argument supplied for foreach() in /home/nao.interessa.com.br/public/wp-content/themes/tema-coletivo-master/inc/customizer-update-fields.php on line 40

Call Stack:
    0.0002     243496   1. {main}() /home/nao.interessa.com.br/public/wp-admin/themes.php:0
    0.0003     244840   2. require_once('/home/nao.interessa.com.br/public/wp-admin/admin.php') /home/nao.interessa.com.br/public/wp-admin/themes.php:10
    2.1002    8833392   3. do_action() /home/nao.interessa.com.br/public/wp-admin/admin.php:156
    2.1002    8834064   4. WP_Hook->do_action() /home/nao.interessa.com.br/public/wp-includes/plugin.php:453
    2.1002    8834160   5. WP_Hook->apply_filters() /home/nao.interessa.com.br/public/wp-includes/class-wp-hook.php:310
    2.1028    8935808   6. call_user_func_array:{/home/nao.interessa.com.br/public/wp-includes/class-wp-hook.php:286}() /home/nao.interessa.com.br/public/wp-includes/class-wp-hook.php:286
    2.1028    8936208   7. ColetivoWP_Update_Customizer->update_theme_mod() /home/nao.interessa.com.br/public/wp-includes/class-wp-hook.php:286
```

Observei também que a pasta ficou nomeada como tema-coletivo-master. Será que podemos fornecer o download de outra forma?

**Comment by everaldomatias** [comment]
@rodineicosta Não é necessário. Antes de subir ele para o seu site você pode remover deixando apenas tema-coletivo como nome da pasta.

Mas se já está usando o tema sugiro deixar assim, porque mudar com ele rodando pode te fazer perder as configs.

**Comment by rodineicosta** [comment]
@everaldomatias Meu comentário foi justamente por conta do erro que apareceu. Mas, seria melhor ver o log pra entender o erro.

**Comment by rodineicosta** [comment]
@everaldomatias Certo. No início, me pareceu uma bobagem propor isso. Mas, percebi que poderia interferir no funcionamento. De outro modo, é melhor o usuário final instalar diretamente do repositório de temas. Assim, não apresentará esse problema. Para usuários do GitHub, basta uma orientação no README.md.
