### ISSUE TITLE
Ordem das Seções

### ISSUE THREAD

**Issue by diegorojas** [redelivre/tema-coletivo#3]
Implementação de uma opção para ordenar as seções da página inicial do site com Drag & Drop usando os boxers repeaters para gerar uma interface no Customizer para se fazer essas trocas por lá

**Comment by diegorojas** [comment]
![image](https://user-images.githubusercontent.com/3632627/30305473-72855430-9749-11e7-9dc5-04f233227935.png)

Sobrou esse adicionar item ai do repeater... um dia ele vai existir.. hehe.. mas por hora não deveria aparecer... oculta ai ou oculto eu via css?

**Comment by matheusgimenez** [comment]
@diegorojas ops, rs. Eh pra remover com css mesmo.. acabei esquecendo, rs
